apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
defmodule NervesHubAPIWeb.Router do
  use NervesHubAPIWeb, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :user do
    plug(NervesHubAPIWeb.Plugs.User)
  end

  pipeline :org do
    plug(NervesHubAPIWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubAPIWeb.Plugs.Product)
  end

  pipeline :device do
    plug(NervesHubAPIWeb.Plugs.Device)
  end

  scope "/health", NervesHubAPIWeb do
    pipe_through(:api)

    get("/", HealthCheckController, :health_check)
  end

  scope "/users", NervesHubAPIWeb do
    pipe_through(:api)

    post("/register", UserController, :register)
    post("/auth", UserController, :auth)
    post("/login", UserController, :login)
    post("/sign", UserController, :sign)
  end

  scope "/", NervesHubAPIWeb do
    pipe_through(:api)
    pipe_through(:user)

    scope "/users" do
      get("/me", UserController, :me)
    end

    scope "/orgs" do
      scope "/:org_name" do
        pipe_through(:org)

        scope "/users" do
          get("/", OrgUserController, :index)
          post("/", OrgUserController, :add)
          get("/:username", OrgUserController, :show)
          put("/:username", OrgUserController, :update)
          delete("/:username", OrgUserController, :remove)
        end

        scope "/keys" do
          get("/", KeyController, :index)
          post("/", KeyController, :create)
          get("/:name", KeyController, :show)
          delete("/:name", KeyController, :delete)
        end

        scope "/ca_certificates" do
          get("/", CACertificateController, :index)
          post("/", CACertificateController, :create)
          get("/:serial", CACertificateController, :show)
          delete("/:serial", CACertificateController, :delete)
        end

        scope "/jitp" do
          get("/:ski", JITPController, :show)
        end

        # The /org/:org_id/device* endpoints should return an error
        scope "/devices" do
          get("/", DeviceController, :error_deprecated)
          post("/", DeviceController, :error_deprecated)
          post("/auth", DeviceController, :error_deprecated)

          scope "/:device_identifier" do
            get("/", DeviceController, :error_deprecated)
            delete("/", DeviceController, :error_deprecated)
            put("/", DeviceController, :error_deprecated)

            scope "/certificates" do
              get("/", DeviceController, :error_deprecated)
              post("/sign", DeviceController, :error_deprecated)
            end
          end
        end

        scope "/products" do
          get("/", ProductController, :index)
          post("/", ProductController, :create)

          scope "/:product_name" do
            pipe_through(:product)

            get("/", ProductController, :show)
            delete("/", ProductController, :delete)
            put("/", ProductController, :update)

            scope "/devices" do
              get("/", DeviceController, :index)
              post("/", DeviceController, :create)
              post("/auth", DeviceController, :auth)

              scope "/:device_identifier" do
                pipe_through(:device)
                get("/", DeviceController, :show)
                delete("/", DeviceController, :delete)
                put("/", DeviceController, :update)

                scope "/certificates" do
                  get("/", DeviceCertificateController, :index)
                  get("/:serial", DeviceCertificateController, :show)
                  post("/", DeviceCertificateController, :create)
                  post("/sign", DeviceCertificateController, :sign)
                  delete("/:serial", DeviceCertificateController, :delete)
                end
              end
            end

            scope "/users" do
              get("/", ProductUserController, :index)
              post("/", ProductUserController, :add)
              get("/:username", ProductUserController, :show)
              put("/:username", ProductUserController, :update)
              delete("/:username", ProductUserController, :remove)
            end

            scope "/firmwares" do
              get("/", FirmwareController, :index)
              get("/:uuid", FirmwareController, :show)
              post("/", FirmwareController, :create)
              delete("/:uuid", FirmwareController, :delete)
            end

            scope "/deployments" do
              get("/", DeploymentController, :index)
              post("/", DeploymentController, :create)
              get("/:name", DeploymentController, :show)
              put("/:name", DeploymentController, :update)
              delete("/:name", DeploymentController, :delete)
            end
          end
        end
      end
    end
  end
end

lib/nerves_hub_web/router.ex
defmodule NervesHubWeb.Router do
  use NervesHubWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {NervesHubWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(NervesHubWeb.Plugs.SetLocale)
  end

  pipeline :logged_in do
    plug(NervesHubWeb.Plugs.FetchUser)
    plug(NervesHubWeb.Plugs.EnsureLoggedIn)
  end

  pipeline :live_logged_in do
    plug(NervesHubWeb.Plugs.EnsureAuthenticated)
  end

  pipeline :admins_only do
    plug(NervesHubWeb.Plugs.AdminBasicAuth)
  end

  pipeline :org do
    plug(NervesHubWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubWeb.Plugs.Product)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :api_user do
    plug(NervesHubWeb.API.Plugs.User)
  end

  pipeline :api_org do
    plug(NervesHubWeb.API.Plugs.Org)
  end

  pipeline :api_product do
    plug(NervesHubWeb.API.Plugs.Product)
  end

  pipeline :api_device do
    plug(NervesHubWeb.API.Plugs.Device)
  end

  scope("/api", NervesHubWeb.API, as: :api) do
    pipe_through(:api)

    get("/health", HealthCheckController, :health_check)

    post("/users/auth", UserController, :auth)
    post("/users/login", UserController, :login)

    scope "/devices" do
      pipe_through([:api_user])

      get("/:identifier", DeviceController, :show)
      post("/:identifier/reboot", DeviceController, :reboot)
      post("/:identifier/reconnect", DeviceController, :reconnect)
      post("/:identifier/code", DeviceController, :code)
      post("/:identifier/upgrade", DeviceController, :upgrade)
      post("/:identifier/move", DeviceController, :move)
      delete("/:identifier/penalty", DeviceController, :penalty)

      get("/:identifier/scripts", ScriptController, :index)
      post("/:identifier/scripts/:id", ScriptController, :send)
    end

    scope "/" do
      pipe_through([:api_user])

      get("/users/me", UserController, :me)

      scope "/orgs" do
        scope "/:org_name" do
          pipe_through([:api_org])

          scope "/users" do
            get("/", OrgUserController, :index)
            post("/", OrgUserController, :add)
            get("/:user_id", OrgUserController, :show)
            put("/:user_id", OrgUserController, :update)
            delete("/:user_id", OrgUserController, :remove)
          end

          scope "/keys" do
            get("/", KeyController, :index)
            post("/", KeyController, :create)
            get("/:name", KeyController, :show)
            delete("/:name", KeyController, :delete)
          end

          scope "/ca_certificates" do
            get("/", CACertificateController, :index)
            post("/", CACertificateController, :create)
            get("/:serial", CACertificateController, :show)
            delete("/:serial", CACertificateController, :delete)
          end

          scope "/products" do
            get("/", ProductController, :index)
            post("/", ProductController, :create)

            scope "/:product_name" do
              pipe_through([:api_product])

              get("/", ProductController, :show)
              delete("/", ProductController, :delete)
              put("/", ProductController, :update)

              scope "/devices" do
                get("/", DeviceController, :index)
                post("/", DeviceController, :create)
                post("/auth", DeviceController, :auth)

                scope "/:identifier" do
                  pipe_through([:api_device])

                  get("/", DeviceController, :show)
                  delete("/", DeviceController, :delete)
                  put("/", DeviceController, :update)
                  post("/reboot", DeviceController, :reboot)
                  post("/reconnect", DeviceController, :reconnect)
                  post("/code", DeviceController, :code)
                  post("/upgrade", DeviceController, :upgrade)
                  delete("/penalty", DeviceController, :penalty)

                  scope "/certificates" do
                    get("/", DeviceCertificateController, :index)
                    get("/:serial", DeviceCertificateController, :show)
                    post("/", DeviceCertificateController, :create)
                    delete("/:serial", DeviceCertificateController, :delete)
                  end
                end
              end

              scope "/firmwares" do
                get("/", FirmwareController, :index)
                get("/:uuid", FirmwareController, :show)
                post("/", FirmwareController, :create)
                delete("/:uuid", FirmwareController, :delete)
              end

              scope "/deployments" do
                get("/", DeploymentController, :index)
                post("/", DeploymentController, :create)
                get("/:name", DeploymentController, :show)
                put("/:name", DeploymentController, :update)
                delete("/:name", DeploymentController, :delete)
              end
            end
          end
        end
      end
    end
  end

  scope "/", NervesHubWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    get("/logout", SessionController, :delete)

    get("/register", AccountController, :new)
    post("/register", AccountController, :create)

    get("/password-reset", PasswordResetController, :new)
    post("/password-reset", PasswordResetController, :create)
    get("/password-reset/:token", PasswordResetController, :new_password_form)
    put("/password-reset/:token", PasswordResetController, :reset)

    get("/invite/:token", AccountController, :invite)
    post("/invite/:token", AccountController, :accept_invite)
  end

  scope "/org/:org_name/:product_name", NervesHubWeb do
    pipe_through([:browser, :logged_in, :org, :product])

    get("/devices/export", ProductController, :devices_export)

    scope "/devices/:identifier" do
      get("/console", DeviceController, :console)
      get("/certificate/:serial/download", DeviceController, :download_certificate)
      get("/audit_logs/download", DeviceController, :export_audit_logs)
    end

    get("/artifacts/:uuid/download", DownloadController, :archive)
    get("/firmware/:uuid/download", DownloadController, :firmware)
    get("/deployments/:name/audit_logs/download", DeploymentController, :export_audit_logs)
  end

  scope "/", NervesHubWeb do
    pipe_through([:browser, :live_logged_in])

    live_session :account,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :clean} do

      live("/account", Live.Account, :edit)
      live("/account/delete", Live.Account, :delete)
      live("/account/tokens", Live.AccountTokens, :index)
      live("/account/tokens/new", Live.AccountTokens, :new)

      live("/orgs", Live.Orgs.Index)
      live("/orgs/new", Live.Orgs.New)
    end

    live_session :org,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser
      ] do
      live("/org/:org_name", Live.Org.Products, :index)
      live("/org/:org_name/new", Live.Org.Products, :new)
      live("/org/:org_name/settings", Live.Org.Settings)
      live("/org/:org_name/settings/keys", Live.Org.SigningKeys, :index)
      live("/org/:org_name/settings/keys/new", Live.Org.SigningKeys, :new)
      live("/org/:org_name/settings/users", Live.Org.Users, :index)
      live("/org/:org_name/settings/users/invite", Live.Org.Users, :invite)
      live("/org/:org_name/settings/users/:user_id/edit", Live.Org.Users, :edit)
      live("/org/:org_name/settings/certificates", Live.Org.CertificateAuthorities, :index)
      live("/org/:org_name/settings/certificates/new", Live.Org.CertificateAuthorities, :new)
      live("/org/:org_name/settings/delete", Live.Org.Delete)

      live(
        "/org/:org_name/settings/certificates/:serial/edit",
        Live.Org.CertificateAuthorities,
        :edit
      )
    end

    live_session :product,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser,
        NervesHubWeb.Mounts.FetchProduct
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :live} do

      live("/org/:org_name/:product_name/dashboard", Live.Dashboard.Index)

      live("/org/:org_name/:product_name/devices", Live.Devices.Index)
      live("/org/:org_name/:product_name/devices/new", Live.Devices.New)
      live("/org/:org_name/:product_name/devices/:device_identifier", Live.Devices.Show)

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/health",
        Live.Devices.DeviceHealth
      )

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/settings",
        Live.Devices.Settings
      )

      live("/org/:org_name/:product_name/firmware", Live.Firmware, :index)
      live("/org/:org_name/:product_name/firmware/upload", Live.Firmware, :upload)
      live("/org/:org_name/:product_name/firmware/:firmware_uuid", Live.Firmware, :show)

      live("/org/:org_name/:product_name/artifacts", Live.Archives, :index)
      live("/org/:org_name/:product_name/artifacts/upload", Live.Archives, :upload)
      live("/org/:org_name/:product_name/artifacts/:archive_uuid", Live.Archives, :show)

      live("/org/:org_name/:product_name/deployments", Live.Deployments.Index)
      live("/org/:org_name/:product_name/deployments/new", Live.Deployments.New)

lib/nerves_hub_web/live/org/delete.ex
defmodule NervesHubWeb.Live.Org.Delete do
  use NervesHubWeb, :updated_live_view

  alias NervesHub.Accounts

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    socket
    |> page_title("Delete Organization - #{socket.assigns.org.name}")
    |> assign(:form, to_form(%{}))
    |> ok()
  end

  @impl Phoenix.LiveView
  def handle_event("delete", params, socket) do
    authorized!(:"organization:delete", socket.assigns.org_user)

    if params["confirm_name"] == socket.assigns.org.name do
      case Accounts.soft_delete_org(socket.assigns.org) do
        {:ok, _org} ->
          socket
          |> put_flash(
            :info,
            "The Organization #{socket.assigns.org.name} has successfully been deleted"
          )
          |> push_navigate(to: ~p"/orgs")
          |> noreply()

        {:error, _changeset} ->
          socket
          |> put_flash(
            :error,
            "There was an error deleting the Organization #{socket.assigns.org.name}. Please contact support."
          )
          |> noreply()
      end
    else
      socket
      |> put_flash(:error, "Please type #{socket.assigns.org.name} to confirm.")
      |> noreply()
    end
  end
end

lib/nerves_hub_web/live/org/products.ex
defmodule NervesHubWeb.Live.Org.Products do
  use NervesHubWeb, :updated_live_view

  alias NervesHub.Products
  alias NervesHub.Products.Product

  embed_templates("product_templates/*")

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl Phoenix.LiveView
  def handle_params(params, _url, socket) do
    socket
    |> apply_action(socket.assigns.live_action, params)
    |> noreply()
  end

  defp apply_action(socket, :index, _params) do
    products = Products.get_products_by_user_and_org(socket.assigns.user, socket.assigns.org)

    socket
    |> page_title("Products - #{socket.assigns.org.name}")
    |> assign(:products, products)
    |> render_with(&products_template/1)
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> page_title("New Product - #{socket.assigns.org.name}")
    |> assign(:form, to_form(Products.change_product(%Product{})))
    |> render_with(&new_product_template/1)
  end

  @impl Phoenix.LiveView
  def handle_event("create_product", %{"product" => product_params}, socket) do
    authorized!(:"product:create", socket.assigns.org_user)

    params = Enum.into(product_params, %{"org_id" => socket.assigns.org.id})

    case Products.create_product(params) do
      {:ok, product} ->
        socket
        |> put_flash(:info, "Product created successfully.")
        |> push_navigate(to: "/org/#{socket.assigns.org.name}/#{product.name}/devices")
        |> noreply()

      {:error, %Ecto.Changeset{} = changeset} ->
        socket
        |> assign(:form, to_form(changeset))
        |> noreply()
    end
  end
end

lib/nerves_hub_web/live/orgs/index.ex
defmodule NervesHubWeb.Live.Orgs.Index do
  use NervesHubWeb, :updated_live_view

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :page_title, "Organizations")}
  end
end

lib/nerves_hub_web/live/org/user_templates/edit_user_template.html.heex
<h1>
  <%= @membership.user.name %>
</h1>

<.form :let={f} for={@form} phx-submit="update-org-user">
  <div class="form-group">
    <label for="role_input" class="tooltip-label h3 mb-1">
      <span>Role</span>
    </label>
    <div class="pos-rel">
      <%= select(f, :role, Utils.role_options(), class: "form-control", id: "role_input") %>
      <div class="select-icon"></div>
    </div>
    <div class="has-error"><%= error_tag(f, :role) %></div>
  </div>

  <div class="button-submit-wrapper">
    <.link class="btn btn-outline-light" patch={~p"/org/#{@org.name}/settings/users"}>Cancel</.link>
    <%= submit("Update", class: "btn btn-primary") %>
  </div>
</.form>

lib/nerves_hub_web/live/org/user_templates/invite_template.html.heex
<h1>
  Add New User
</h1>

<h5>An invitation will be sent to join <%= @org.name %>. Invites expire in 48 hours.</h5>

<.form :let={f} for={@form} phx-submit="send_invite">
  <%= if f.action do %>
    <div class="alert alert-danger">
      <p>Something went wrong, please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group mt-6">
    <label for="email_input" class="h3 mb-1">Email</label>
    <%= email_input(f, :email, class: "form-control", id: "email_input", value: assigns[:email]) %>
    <div class="has-error"><%= error_tag(f, :email) %></div>
    <div class="has-error"><%= error_tag(f, :org_users) %></div>
  </div>

  <div class="form-group">
    <label for="role_input" class="tooltip-label h3 mb-1">
      <span>Role</span>
      <span class="tooltip-info"></span>
      <span class="tooltip-text">Defines the type of access this user has in this org</span>
    </label>
    <div class="pos-rel">
      <%= select(f, :role, Utils.role_options(), selected: :view, class: "form-control") %>
      <div class="select-icon"></div>
    </div>
  </div>

  <div class="button-submit-wrapper">
    <.link class="btn btn-outline-light" patch={~p"/org/#{@org.name}/settings/users"}>Cancel</.link>
    <%= submit("Send Invitation", class: "btn btn-primary") %>
  </div>
</.form>

lib/nerves_hub_web/live/org/user_templates/users_template.html.heex
<%= if !Enum.empty?(@invites) do %>
  <h1>Outstanding Invites</h1>

  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Invite Link</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= for invite <- @invites do %>
        <tr>
          <td><%= invite.email %></td>
          <td><pre style="background: white; margin: auto;"><%= Routes.account_url(@socket, :invite, invite.token) %></pre></td>
          <td :if={authorized?(:"org_user:invite:rescind", @org_user)}>
            <.link class="btn btn-outline-light" phx-click="rescind_invite" phx-value-invite_token={invite.token} data-confirm="Are you sure you want to rescind the invite?">
              Rescind
            </.link>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="action-row">
  <h1>Users</h1>
  <.link navigate={~p"/org/#{@org.name}/settings/users/invite"} class="btn btn-outline-light btn-action" aria-label="Add new user">
    <span class="button-icon add"></span>
    <span class="action-text">Add New User</span>
  </.link>
</div>

<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th>User name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Added on</th>
    </tr>
  </thead>
  <tbody>
    <%= for org_user <- @org_users do %>
      <tr class="item">
        <td>
          <div class="mobile-label help-text">User name</div>
          <%= org_user.user.name %>
        </td>
        <td>
          <div class="mobile-label help-text">Email</div>
          <%= org_user.user.email %>
        </td>
        <td class="tt-c">
          <div class="mobile-label help-text">Role</div>
          <%= org_user.role %>
        </td>
        <td>
          <div class="mobile-label help-text">Added on</div>
          <div class="date-time"><%= org_user.user.inserted_at %></div>
        </td>
        <td :if={authorized?(:"org_user:delete", @org_user) && org_user.user.id != assigns.user.id} class="actions">
          <div class="dropdown options">
            <a class="dropdown-toggle options" href="#" id={"org-user-#{org_user.id}"} data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="/images/icons/more.svg" alt="options" />
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <.link patch={~p"/org/#{@org.name}/settings/users/#{org_user.user_id}/edit"} class="dropdown-item">
                Edit
              </.link>
              <div class="dropdown-divider"></div>
              <.link
                :if={authorized?(:"org_user:delete", @org_user)}
                class="dropdown-item"
                phx-click="delete_org_user"
                phx-value-user_id={org_user.user_id}
                data-confirm="Are you sure you want to remove this user? This can not be undone."
              >
                Delete
              </.link>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>