apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
defmodule NervesHubAPIWeb.Router do
  use NervesHubAPIWeb, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :user do
    plug(NervesHubAPIWeb.Plugs.User)
  end

  pipeline :org do
    plug(NervesHubAPIWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubAPIWeb.Plugs.Product)
  end

  pipeline :device do
    plug(NervesHubAPIWeb.Plugs.Device)
  end

  scope "/health", NervesHubAPIWeb do
    pipe_through(:api)

    get("/", HealthCheckController, :health_check)
  end

  scope "/users", NervesHubAPIWeb do
    pipe_through(:api)

    post("/register", UserController, :register)
    post("/auth", UserController, :auth)
    post("/login", UserController, :login)
    post("/sign", UserController, :sign)
  end

  scope "/", NervesHubAPIWeb do
    pipe_through(:api)
    pipe_through(:user)

    scope "/users" do
      get("/me", UserController, :me)
    end

    scope "/orgs" do
      scope "/:org_name" do
        pipe_through(:org)

        scope "/users" do
          get("/", OrgUserController, :index)
          post("/", OrgUserController, :add)
          get("/:username", OrgUserController, :show)
          put("/:username", OrgUserController, :update)
          delete("/:username", OrgUserController, :remove)
        end

        scope "/keys" do
          get("/", KeyController, :index)
          post("/", KeyController, :create)
          get("/:name", KeyController, :show)
          delete("/:name", KeyController, :delete)
        end

        scope "/ca_certificates" do
          get("/", CACertificateController, :index)
          post("/", CACertificateController, :create)
          get("/:serial", CACertificateController, :show)
          delete("/:serial", CACertificateController, :delete)
        end

        scope "/jitp" do
          get("/:ski", JITPController, :show)
        end

        # The /org/:org_id/device* endpoints should return an error
        scope "/devices" do
          get("/", DeviceController, :error_deprecated)
          post("/", DeviceController, :error_deprecated)
          post("/auth", DeviceController, :error_deprecated)

          scope "/:device_identifier" do
            get("/", DeviceController, :error_deprecated)
            delete("/", DeviceController, :error_deprecated)
            put("/", DeviceController, :error_deprecated)

            scope "/certificates" do
              get("/", DeviceController, :error_deprecated)
              post("/sign", DeviceController, :error_deprecated)
            end
          end
        end

        scope "/products" do
          get("/", ProductController, :index)
          post("/", ProductController, :create)

          scope "/:product_name" do
            pipe_through(:product)

            get("/", ProductController, :show)
            delete("/", ProductController, :delete)
            put("/", ProductController, :update)

            scope "/devices" do
              get("/", DeviceController, :index)
              post("/", DeviceController, :create)
              post("/auth", DeviceController, :auth)

              scope "/:device_identifier" do
                pipe_through(:device)
                get("/", DeviceController, :show)
                delete("/", DeviceController, :delete)
                put("/", DeviceController, :update)

                scope "/certificates" do
                  get("/", DeviceCertificateController, :index)
                  get("/:serial", DeviceCertificateController, :show)
                  post("/", DeviceCertificateController, :create)
                  post("/sign", DeviceCertificateController, :sign)
                  delete("/:serial", DeviceCertificateController, :delete)
                end
              end
            end

            scope "/users" do
              get("/", ProductUserController, :index)
              post("/", ProductUserController, :add)
              get("/:username", ProductUserController, :show)
              put("/:username", ProductUserController, :update)
              delete("/:username", ProductUserController, :remove)
            end

            scope "/firmwares" do
              get("/", FirmwareController, :index)
              get("/:uuid", FirmwareController, :show)
              post("/", FirmwareController, :create)
              delete("/:uuid", FirmwareController, :delete)
            end

            scope "/deployments" do
              get("/", DeploymentController, :index)
              post("/", DeploymentController, :create)
              get("/:name", DeploymentController, :show)
              put("/:name", DeploymentController, :update)
              delete("/:name", DeploymentController, :delete)
            end
          end
        end
      end
    end
  end
end

lib/nerves_hub_web/router.ex
defmodule NervesHubWeb.Router do
  use NervesHubWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {NervesHubWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(NervesHubWeb.Plugs.SetLocale)
  end

  pipeline :logged_in do
    plug(NervesHubWeb.Plugs.FetchUser)
    plug(NervesHubWeb.Plugs.EnsureLoggedIn)
  end

  pipeline :live_logged_in do
    plug(NervesHubWeb.Plugs.EnsureAuthenticated)
  end

  pipeline :admins_only do
    plug(NervesHubWeb.Plugs.AdminBasicAuth)
  end

  pipeline :org do
    plug(NervesHubWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubWeb.Plugs.Product)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :api_user do
    plug(NervesHubWeb.API.Plugs.User)
  end

  pipeline :api_org do
    plug(NervesHubWeb.API.Plugs.Org)
  end

  pipeline :api_product do
    plug(NervesHubWeb.API.Plugs.Product)
  end

  pipeline :api_device do
    plug(NervesHubWeb.API.Plugs.Device)
  end

  scope("/api", NervesHubWeb.API, as: :api) do
    pipe_through(:api)

    get("/health", HealthCheckController, :health_check)

    post("/users/auth", UserController, :auth)
    post("/users/login", UserController, :login)

    scope "/devices" do
      pipe_through([:api_user])

      get("/:identifier", DeviceController, :show)
      post("/:identifier/reboot", DeviceController, :reboot)
      post("/:identifier/reconnect", DeviceController, :reconnect)
      post("/:identifier/code", DeviceController, :code)
      post("/:identifier/upgrade", DeviceController, :upgrade)
      post("/:identifier/move", DeviceController, :move)
      delete("/:identifier/penalty", DeviceController, :penalty)

      get("/:identifier/scripts", ScriptController, :index)
      post("/:identifier/scripts/:id", ScriptController, :send)
    end

    scope "/" do
      pipe_through([:api_user])

      get("/users/me", UserController, :me)

      scope "/orgs" do
        scope "/:org_name" do
          pipe_through([:api_org])

          scope "/users" do
            get("/", OrgUserController, :index)
            post("/", OrgUserController, :add)
            get("/:user_id", OrgUserController, :show)
            put("/:user_id", OrgUserController, :update)
            delete("/:user_id", OrgUserController, :remove)
          end

          scope "/keys" do
            get("/", KeyController, :index)
            post("/", KeyController, :create)
            get("/:name", KeyController, :show)
            delete("/:name", KeyController, :delete)
          end

          scope "/ca_certificates" do
            get("/", CACertificateController, :index)
            post("/", CACertificateController, :create)
            get("/:serial", CACertificateController, :show)
            delete("/:serial", CACertificateController, :delete)
          end

          scope "/products" do
            get("/", ProductController, :index)
            post("/", ProductController, :create)

            scope "/:product_name" do
              pipe_through([:api_product])

              get("/", ProductController, :show)
              delete("/", ProductController, :delete)
              put("/", ProductController, :update)

              scope "/devices" do
                get("/", DeviceController, :index)
                post("/", DeviceController, :create)
                post("/auth", DeviceController, :auth)

                scope "/:identifier" do
                  pipe_through([:api_device])

                  get("/", DeviceController, :show)
                  delete("/", DeviceController, :delete)
                  put("/", DeviceController, :update)
                  post("/reboot", DeviceController, :reboot)
                  post("/reconnect", DeviceController, :reconnect)
                  post("/code", DeviceController, :code)
                  post("/upgrade", DeviceController, :upgrade)
                  delete("/penalty", DeviceController, :penalty)

                  scope "/certificates" do
                    get("/", DeviceCertificateController, :index)
                    get("/:serial", DeviceCertificateController, :show)
                    post("/", DeviceCertificateController, :create)
                    delete("/:serial", DeviceCertificateController, :delete)
                  end
                end
              end

              scope "/firmwares" do
                get("/", FirmwareController, :index)
                get("/:uuid", FirmwareController, :show)
                post("/", FirmwareController, :create)
                delete("/:uuid", FirmwareController, :delete)
              end

              scope "/deployments" do
                get("/", DeploymentController, :index)
                post("/", DeploymentController, :create)
                get("/:name", DeploymentController, :show)
                put("/:name", DeploymentController, :update)
                delete("/:name", DeploymentController, :delete)
              end
            end
          end
        end
      end
    end
  end

  scope "/", NervesHubWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    get("/logout", SessionController, :delete)

    get("/register", AccountController, :new)
    post("/register", AccountController, :create)

    get("/password-reset", PasswordResetController, :new)
    post("/password-reset", PasswordResetController, :create)
    get("/password-reset/:token", PasswordResetController, :new_password_form)
    put("/password-reset/:token", PasswordResetController, :reset)

    get("/invite/:token", AccountController, :invite)
    post("/invite/:token", AccountController, :accept_invite)
  end

  scope "/org/:org_name/:product_name", NervesHubWeb do
    pipe_through([:browser, :logged_in, :org, :product])

    get("/devices/export", ProductController, :devices_export)

    scope "/devices/:identifier" do
      get("/console", DeviceController, :console)
      get("/certificate/:serial/download", DeviceController, :download_certificate)
      get("/audit_logs/download", DeviceController, :export_audit_logs)
    end

    get("/artifacts/:uuid/download", DownloadController, :archive)
    get("/firmware/:uuid/download", DownloadController, :firmware)
    get("/deployments/:name/audit_logs/download", DeploymentController, :export_audit_logs)
  end

  scope "/", NervesHubWeb do
    pipe_through([:browser, :live_logged_in])

    live_session :account,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :clean} do

      live("/account", Live.Account, :edit)
      live("/account/delete", Live.Account, :delete)
      live("/account/tokens", Live.AccountTokens, :index)
      live("/account/tokens/new", Live.AccountTokens, :new)

      live("/orgs", Live.Orgs.Index)
      live("/orgs/new", Live.Orgs.New)
    end

    live_session :org,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser
      ] do
      live("/org/:org_name", Live.Org.Products, :index)
      live("/org/:org_name/new", Live.Org.Products, :new)
      live("/org/:org_name/settings", Live.Org.Settings)
      live("/org/:org_name/settings/keys", Live.Org.SigningKeys, :index)
      live("/org/:org_name/settings/keys/new", Live.Org.SigningKeys, :new)
      live("/org/:org_name/settings/users", Live.Org.Users, :index)
      live("/org/:org_name/settings/users/invite", Live.Org.Users, :invite)
      live("/org/:org_name/settings/users/:user_id/edit", Live.Org.Users, :edit)
      live("/org/:org_name/settings/certificates", Live.Org.CertificateAuthorities, :index)
      live("/org/:org_name/settings/certificates/new", Live.Org.CertificateAuthorities, :new)
      live("/org/:org_name/settings/delete", Live.Org.Delete)

      live(
        "/org/:org_name/settings/certificates/:serial/edit",
        Live.Org.CertificateAuthorities,
        :edit
      )
    end

    live_session :product,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser,
        NervesHubWeb.Mounts.FetchProduct
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :live} do

      live("/org/:org_name/:product_name/dashboard", Live.Dashboard.Index)

      live("/org/:org_name/:product_name/devices", Live.Devices.Index)
      live("/org/:org_name/:product_name/devices/new", Live.Devices.New)
      live("/org/:org_name/:product_name/devices/:device_identifier", Live.Devices.Show)

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/health",
        Live.Devices.DeviceHealth
      )

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/settings",
        Live.Devices.Settings
      )

      live("/org/:org_name/:product_name/firmware", Live.Firmware, :index)
      live("/org/:org_name/:product_name/firmware/upload", Live.Firmware, :upload)
      live("/org/:org_name/:product_name/firmware/:firmware_uuid", Live.Firmware, :show)

      live("/org/:org_name/:product_name/artifacts", Live.Archives, :index)
      live("/org/:org_name/:product_name/artifacts/upload", Live.Archives, :upload)
      live("/org/:org_name/:product_name/artifacts/:archive_uuid", Live.Archives, :show)

      live("/org/:org_name/:product_name/deployments", Live.Deployments.Index)
      live("/org/:org_name/:product_name/deployments/new", Live.Deployments.New)

lib/nerves_hub_web/templates/org_certificate/edit.html.eex
<h1>Edit Certificate Authority</h1>

<%= form_for @changeset, Routes.org_certificate_path(@conn, :update, @org.name, @serial), fn f -> %>
  <div class="form-group">
    <%= label f, :description, for: "description_input" %>
    <%= text_input f, :description , class: "form-control", id: "description_input" %>
    <div class="has-error"><%= error_tag f, :description %></div>
  </div>

  <%= inputs_for f, :jitp, fn fp -> %>
    <label for="jitp_toggle"> Enable Just In Time Provisioning </label>
    <input type="checkbox" name="jitp_toggle" id="jitp_toggle" <%= if f.data.jitp, do: "checked"%>>
    <%= hidden_input fp, :delete, id: "jitp-delete" %>
    <div <%= unless f.data.jitp, do: "hidden"%> id="jitp_form">
      <div class="form-group">
        <label for="description_input" class="tooltip-label h3 mb-1">
          <span>JITP Description</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">Device Description</span>
        </label>
        <%= text_input fp, :description, class: "form-control", id: "description_input" %>
        <div class="has-error"><%= error_tag fp, :description %></div>
      </div>

      <div class="form-group" aria-hidden="true">
        <label for="tag_input" class="tooltip-label h3 mb-1">
          <span>JITP Tags</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">Tags are used by deployments to target a device. A device must have matching tag(s) for the deployment to update it</span>
        </label>
        <%= text_input fp, :tags, class: "form-control", id: "tag_input" %>
        <div class="has-error"><%= error_tag fp, :tags %></div>
      </div>

      <div class="form-group" aria-hidden="true">
        <label for="tag_input" class="tooltip-label h3 mb-1">
          <span>JITP Product</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">JITP must be configured to use a particular product</span>
        </label>
        <%= select fp, :product_id, Enum.map(@products, &{&1.name, &1.id}), class: "form-control", id: "product_input" %>
        <div class="has-error"><%= error_tag fp, :product_id %></div>
      </div>
    </div>
  <% end %>

  <div class="button-submit-wrapper">
    <%= link "Back", to: Routes.org_certificate_path(@conn, :index, @org.name), class: "btn btn-outline-light" %>
    <%= submit "Update Certificate", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
document.getElementById("jitp_toggle").onclick = function() {
  document.getElementById("jitp_form").hidden = !this.checked;
  document.getElementById("jitp-delete").value = !this.checked;
}
</script>

lib/nerves_hub_web/templates/org_certificate/index.html.eex
<div class="action-row">
  <h1>Certificate Authorities</h1>
  <a class="btn btn-outline-light btn-action" aria-label="Add certificate authority" href="<%= Routes.org_certificate_path(@conn, :new, @org.name) %>">
    <span class="button-icon add"></span>
    <span class="action-text">Add Certificate Authority</span>
  </a>
</div>

<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th>Serial</th>
      <th>Description</th>
      <th>Last used</th>
      <th>Not before</th>
      <th>Not after</th>
      <th>JITP Enabled? </th>
    </tr>
  </thead>
  <tbody>
    <%= for cert <- @certificates do %>
      <tr class="item">
        <td>
          <div class="mobile-label help-text">Serial</div>
          <code class="color-white wb-ba ff-m"><%= format_serial(cert.serial) %></code>
        </td>
        <td>
          <div class="mobile-label help-text">Description</div>
          <%= if is_nil(cert.description) do %>
            -
          <% else %>
            <%= cert.description %>
          <% end %>
        </td>
        <td>
          <div class="mobile-label help-text">Last used</div>
          <%= if !is_nil(cert.last_used) do %>
            <%= DateTimeFormat.from_now(cert.last_used) %>
          <% else %>
            <span class="text-muted">Never</span>
          <% end %>
        </td>
        <td>
          <div class="mobile-label help-text">Not before</div>
          <div class="date-time"><%= cert.not_before %></div>
        </td>
        <td>
          <div class="mobile-label help-text">Not after</div>
          <div class="date-time"><%= cert.not_after %></div>
        </td>
        <td>
          <span class="text-muted"><%= if is_nil(cert.jitp), do: "no", else: "yes" %></span>
        </td>
        <td class="actions">
          <div class="mobile-label help-text">Actions</div>
          <div class="dropdown options">
            <a class="dropdown-toggle options" href="#" id="<%= cert.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="mobile-label pr-2">Open</div>
              <img src="/images/icons/more.svg" alt="options" />
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link "Edit", class: "dropdown-item", to: Routes.org_certificate_path(@conn, :edit, @org.name, cert.serial) %>
              <%= link "Delete", class: "dropdown-item", to: Routes.org_certificate_path(@conn, :delete, @org.name, cert.serial), method: :delete, data: [confirm: "Are you sure you want to delete this certificate? This can not be undone."] %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/nerves_hub_web/templates/org_certificate/new.html.eex
<h1>New Certificate Authority</h1>

<%= form_for @changeset, Routes.org_certificate_path(@conn, :create, @org.name), [multipart: true], fn f -> %>
  <h3> Step 1 </h3>
  <p> Generate a key pair for the private key verification certificate </p>
  <pre><code class="language-bash">
  openssl genrsa -out verificationCert.key 2048
  </code></pre>

  <h3> Step 2 </h3>
  <p> Copy this registration code to your clipboard </p>
  <pre><code class="language-bash">
  <%= @registration_code %>
  </code></pre>

  <h3> Step 3 </h3>
  <p> Create a CSR with this registration code </p>
  <pre><code class="language-bash">
  openssl req -new -key verificationCert.key -out verificationCert.csr
  </code></pre>

  <p> Put the registration code in the <b> Common Name </b> field </p>
  <pre><code class="language-bash">
  Country Name (2 letter code) [AU]:
  State or Province Name (full name) [Some-State]:
  Locality Name (eg, city) []:
  Organization Name (eg, company) [Internet Widgits Pty Ltd]:
  Organizational Unit Name (eg, section) []:
  Common Name (e.g. server FQDN or YOUR name) []: <%= @registration_code %>
  Email Address []:
  </code></pre>

  <h3> Step 4 </h3>
  <p> Use the CSR that was signed with the CA private key to create a private key verification certificate </p>
  <pre><code class="language-bash">
  openssl x509 -req -in verificationCert.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out verificationCert.crt -days 500 -sha256
  </code></pre>

  <div class="form-group">
    <%= label f, :description, for: "description_input" %>
    <%= text_input f, :description , class: "form-control", id: "description_input" %>
    <div class="has-error"><%= error_tag f, :description %></div>
  </div>

  <%= inputs_for f, :jitp, fn fp -> %>
    <label for="jitp_toggle"> Enable Just In Time Provisioning </label>
    <%= checkbox fp, :jitp_toggle, id: "jitp_toggle" %>
    <div hidden id="jitp_form">
      <div class="form-group">
        <label for="description_input" class="tooltip-label h3 mb-1">
          <span>JITP Description</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">Device Description</span>
        </label>
        <%= text_input fp, :description, class: "form-control", id: "description_input" %>
        <div class="has-error"><%= error_tag fp, :description %></div>
      </div>

      <div class="form-group" aria-hidden="true">
        <label for="tag_input" class="tooltip-label h3 mb-1">
          <span>JITP Tags</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">Tags are used by deployments to target a device. A device must have matching tag(s) for the deployment to update it</span>
        </label>
        <%= text_input fp, :tags, class: "form-control", id: "tag_input" %>
        <div class="has-error"><%= error_tag fp, :tags %></div>
      </div>

      <div class="form-group" aria-hidden="true">
        <label for="tag_input" class="tooltip-label h3 mb-1">
          <span>JITP Product</span>
          <span class="tooltip-info"></span>
          <span class="tooltip-text">JITP must be configured to use a particular product</span>
        </label>
        <%= select fp, :product_id, Enum.map(@products, &{&1.name, &1.id}), class: "form-control", id: "product_input", prompt: "Select Product" %>
        <div class="has-error"><%= error_tag fp, :product_id %></div>
      </div>
    </div>
  <% end %>

  <div class="form-group custom-upload-group">
    <%= label f, :cert, "Upload a Certificate Authority file (rootCA.pem)", class: "custom-upload-label not-selected", for: "cert_input" %>
    <%= file_input f, :cert, required: true, class: "custom-upload-input hidden", id: "cert_input", accept: ".pem" %>
    <div class="has-error"><%= error_tag f, :cert %></div>
  </div>

  <div class="form-group custom-upload-group">
    <%= label f, :csr, "Upload a Certificate Authority file (verificationCert.crt)", class: "custom-upload-label not-selected", for: "csr_input" %>
    <%= file_input f, :csr, required: true, class: "custom-upload-input hidden", id: "csr_input", accept: ".crt" %>
    <div class="has-error"><%= error_tag f, :csr %></div>
  </div>

  <div class="button-submit-wrapper">
    <%= link "Back", to: Routes.org_certificate_path(@conn, :index, @org.name), class: "btn btn-outline-light" %>
    <%= submit "Create Certificate", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
document.getElementById("jitp_toggle").onclick = function() {
  document.getElementById("jitp_form").hidden = !this.checked;
}
</script>