apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
defmodule NervesHubAPIWeb.Router do
  use NervesHubAPIWeb, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :user do
    plug(NervesHubAPIWeb.Plugs.User)
  end

  pipeline :org do
    plug(NervesHubAPIWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubAPIWeb.Plugs.Product)
  end

  pipeline :device do
    plug(NervesHubAPIWeb.Plugs.Device)
  end

  scope "/health", NervesHubAPIWeb do
    pipe_through(:api)

    get("/", HealthCheckController, :health_check)
  end

  scope "/users", NervesHubAPIWeb do
    pipe_through(:api)

    post("/register", UserController, :register)
    post("/auth", UserController, :auth)
    post("/login", UserController, :login)
    post("/sign", UserController, :sign)
  end

  scope "/", NervesHubAPIWeb do
    pipe_through(:api)
    pipe_through(:user)

    scope "/users" do
      get("/me", UserController, :me)
    end

    scope "/orgs" do
      scope "/:org_name" do
        pipe_through(:org)

        scope "/users" do
          get("/", OrgUserController, :index)
          post("/", OrgUserController, :add)
          get("/:username", OrgUserController, :show)
          put("/:username", OrgUserController, :update)
          delete("/:username", OrgUserController, :remove)
        end

        scope "/keys" do
          get("/", KeyController, :index)
          post("/", KeyController, :create)
          get("/:name", KeyController, :show)
          delete("/:name", KeyController, :delete)
        end

        scope "/ca_certificates" do
          get("/", CACertificateController, :index)
          post("/", CACertificateController, :create)
          get("/:serial", CACertificateController, :show)
          delete("/:serial", CACertificateController, :delete)
        end

        scope "/jitp" do
          get("/:ski", JITPController, :show)
        end

        # The /org/:org_id/device* endpoints should return an error
        scope "/devices" do
          get("/", DeviceController, :error_deprecated)
          post("/", DeviceController, :error_deprecated)
          post("/auth", DeviceController, :error_deprecated)

          scope "/:device_identifier" do
            get("/", DeviceController, :error_deprecated)
            delete("/", DeviceController, :error_deprecated)
            put("/", DeviceController, :error_deprecated)

            scope "/certificates" do
              get("/", DeviceController, :error_deprecated)
              post("/sign", DeviceController, :error_deprecated)
            end
          end
        end

        scope "/products" do
          get("/", ProductController, :index)
          post("/", ProductController, :create)

          scope "/:product_name" do
            pipe_through(:product)

            get("/", ProductController, :show)
            delete("/", ProductController, :delete)
            put("/", ProductController, :update)

            scope "/devices" do
              get("/", DeviceController, :index)
              post("/", DeviceController, :create)
              post("/auth", DeviceController, :auth)

              scope "/:device_identifier" do
                pipe_through(:device)
                get("/", DeviceController, :show)
                delete("/", DeviceController, :delete)
                put("/", DeviceController, :update)

                scope "/certificates" do
                  get("/", DeviceCertificateController, :index)
                  get("/:serial", DeviceCertificateController, :show)
                  post("/", DeviceCertificateController, :create)
                  post("/sign", DeviceCertificateController, :sign)
                  delete("/:serial", DeviceCertificateController, :delete)
                end
              end
            end

            scope "/users" do
              get("/", ProductUserController, :index)
              post("/", ProductUserController, :add)
              get("/:username", ProductUserController, :show)
              put("/:username", ProductUserController, :update)
              delete("/:username", ProductUserController, :remove)
            end

            scope "/firmwares" do
              get("/", FirmwareController, :index)
              get("/:uuid", FirmwareController, :show)
              post("/", FirmwareController, :create)
              delete("/:uuid", FirmwareController, :delete)
            end

            scope "/deployments" do
              get("/", DeploymentController, :index)
              post("/", DeploymentController, :create)
              get("/:name", DeploymentController, :show)
              put("/:name", DeploymentController, :update)
              delete("/:name", DeploymentController, :delete)
            end
          end
        end
      end
    end
  end
end

lib/nerves_hub_web/router.ex
defmodule NervesHubWeb.Router do
  use NervesHubWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {NervesHubWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(NervesHubWeb.Plugs.SetLocale)
  end

  pipeline :logged_in do
    plug(NervesHubWeb.Plugs.FetchUser)
    plug(NervesHubWeb.Plugs.EnsureLoggedIn)
  end

  pipeline :live_logged_in do
    plug(NervesHubWeb.Plugs.EnsureAuthenticated)
  end

  pipeline :admins_only do
    plug(NervesHubWeb.Plugs.AdminBasicAuth)
  end

  pipeline :org do
    plug(NervesHubWeb.Plugs.Org)
  end

  pipeline :product do
    plug(NervesHubWeb.Plugs.Product)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :api_user do
    plug(NervesHubWeb.API.Plugs.User)
  end

  pipeline :api_org do
    plug(NervesHubWeb.API.Plugs.Org)
  end

  pipeline :api_product do
    plug(NervesHubWeb.API.Plugs.Product)
  end

  pipeline :api_device do
    plug(NervesHubWeb.API.Plugs.Device)
  end

  scope("/api", NervesHubWeb.API, as: :api) do
    pipe_through(:api)

    get("/health", HealthCheckController, :health_check)

    post("/users/auth", UserController, :auth)
    post("/users/login", UserController, :login)

    scope "/devices" do
      pipe_through([:api_user])

      get("/:identifier", DeviceController, :show)
      post("/:identifier/reboot", DeviceController, :reboot)
      post("/:identifier/reconnect", DeviceController, :reconnect)
      post("/:identifier/code", DeviceController, :code)
      post("/:identifier/upgrade", DeviceController, :upgrade)
      post("/:identifier/move", DeviceController, :move)
      delete("/:identifier/penalty", DeviceController, :penalty)

      get("/:identifier/scripts", ScriptController, :index)
      post("/:identifier/scripts/:id", ScriptController, :send)
    end

    scope "/" do
      pipe_through([:api_user])

      get("/users/me", UserController, :me)

      scope "/orgs" do
        scope "/:org_name" do
          pipe_through([:api_org])

          scope "/users" do
            get("/", OrgUserController, :index)
            post("/", OrgUserController, :add)
            get("/:user_id", OrgUserController, :show)
            put("/:user_id", OrgUserController, :update)
            delete("/:user_id", OrgUserController, :remove)
          end

          scope "/keys" do
            get("/", KeyController, :index)
            post("/", KeyController, :create)
            get("/:name", KeyController, :show)
            delete("/:name", KeyController, :delete)
          end

          scope "/ca_certificates" do
            get("/", CACertificateController, :index)
            post("/", CACertificateController, :create)
            get("/:serial", CACertificateController, :show)
            delete("/:serial", CACertificateController, :delete)
          end

          scope "/products" do
            get("/", ProductController, :index)
            post("/", ProductController, :create)

            scope "/:product_name" do
              pipe_through([:api_product])

              get("/", ProductController, :show)
              delete("/", ProductController, :delete)
              put("/", ProductController, :update)

              scope "/devices" do
                get("/", DeviceController, :index)
                post("/", DeviceController, :create)
                post("/auth", DeviceController, :auth)

                scope "/:identifier" do
                  pipe_through([:api_device])

                  get("/", DeviceController, :show)
                  delete("/", DeviceController, :delete)
                  put("/", DeviceController, :update)
                  post("/reboot", DeviceController, :reboot)
                  post("/reconnect", DeviceController, :reconnect)
                  post("/code", DeviceController, :code)
                  post("/upgrade", DeviceController, :upgrade)
                  delete("/penalty", DeviceController, :penalty)

                  scope "/certificates" do
                    get("/", DeviceCertificateController, :index)
                    get("/:serial", DeviceCertificateController, :show)
                    post("/", DeviceCertificateController, :create)
                    delete("/:serial", DeviceCertificateController, :delete)
                  end
                end
              end

              scope "/firmwares" do
                get("/", FirmwareController, :index)
                get("/:uuid", FirmwareController, :show)
                post("/", FirmwareController, :create)
                delete("/:uuid", FirmwareController, :delete)
              end

              scope "/deployments" do
                get("/", DeploymentController, :index)
                post("/", DeploymentController, :create)
                get("/:name", DeploymentController, :show)
                put("/:name", DeploymentController, :update)
                delete("/:name", DeploymentController, :delete)
              end
            end
          end
        end
      end
    end
  end

  scope "/", NervesHubWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    get("/logout", SessionController, :delete)

    get("/register", AccountController, :new)
    post("/register", AccountController, :create)

    get("/password-reset", PasswordResetController, :new)
    post("/password-reset", PasswordResetController, :create)
    get("/password-reset/:token", PasswordResetController, :new_password_form)
    put("/password-reset/:token", PasswordResetController, :reset)

    get("/invite/:token", AccountController, :invite)
    post("/invite/:token", AccountController, :accept_invite)
  end

  scope "/org/:org_name/:product_name", NervesHubWeb do
    pipe_through([:browser, :logged_in, :org, :product])

    get("/devices/export", ProductController, :devices_export)

    scope "/devices/:identifier" do
      get("/console", DeviceController, :console)
      get("/certificate/:serial/download", DeviceController, :download_certificate)
      get("/audit_logs/download", DeviceController, :export_audit_logs)
    end

    get("/artifacts/:uuid/download", DownloadController, :archive)
    get("/firmware/:uuid/download", DownloadController, :firmware)
    get("/deployments/:name/audit_logs/download", DeploymentController, :export_audit_logs)
  end

  scope "/", NervesHubWeb do
    pipe_through([:browser, :live_logged_in])

    live_session :account,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :clean} do

      live("/account", Live.Account, :edit)
      live("/account/delete", Live.Account, :delete)
      live("/account/tokens", Live.AccountTokens, :index)
      live("/account/tokens/new", Live.AccountTokens, :new)

      live("/orgs", Live.Orgs.Index)
      live("/orgs/new", Live.Orgs.New)
    end

    live_session :org,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser
      ] do
      live("/org/:org_name", Live.Org.Products, :index)
      live("/org/:org_name/new", Live.Org.Products, :new)
      live("/org/:org_name/settings", Live.Org.Settings)
      live("/org/:org_name/settings/keys", Live.Org.SigningKeys, :index)
      live("/org/:org_name/settings/keys/new", Live.Org.SigningKeys, :new)
      live("/org/:org_name/settings/users", Live.Org.Users, :index)
      live("/org/:org_name/settings/users/invite", Live.Org.Users, :invite)
      live("/org/:org_name/settings/users/:user_id/edit", Live.Org.Users, :edit)
      live("/org/:org_name/settings/certificates", Live.Org.CertificateAuthorities, :index)
      live("/org/:org_name/settings/certificates/new", Live.Org.CertificateAuthorities, :new)
      live("/org/:org_name/settings/delete", Live.Org.Delete)

      live(
        "/org/:org_name/settings/certificates/:serial/edit",
        Live.Org.CertificateAuthorities,
        :edit
      )
    end

    live_session :product,
      on_mount: [
        NervesHubWeb.Mounts.AccountAuth,
        NervesHubWeb.Mounts.CurrentPath,
        NervesHubWeb.Mounts.FetchOrg,
        NervesHubWeb.Mounts.FetchOrgUser,
        NervesHubWeb.Mounts.FetchProduct
      ],
      root_layout: {NervesHubWeb.Layouts, :root},
      layout: {NervesHubWeb.Layouts, :live} do

      live("/org/:org_name/:product_name/dashboard", Live.Dashboard.Index)

      live("/org/:org_name/:product_name/devices", Live.Devices.Index)
      live("/org/:org_name/:product_name/devices/new", Live.Devices.New)
      live("/org/:org_name/:product_name/devices/:device_identifier", Live.Devices.Show)

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/health",
        Live.Devices.DeviceHealth
      )

      live(
        "/org/:org_name/:product_name/devices/:device_identifier/settings",
        Live.Devices.Settings
      )

      live("/org/:org_name/:product_name/firmware", Live.Firmware, :index)
      live("/org/:org_name/:product_name/firmware/upload", Live.Firmware, :upload)
      live("/org/:org_name/:product_name/firmware/:firmware_uuid", Live.Firmware, :show)

      live("/org/:org_name/:product_name/artifacts", Live.Archives, :index)
      live("/org/:org_name/:product_name/artifacts/upload", Live.Archives, :upload)
      live("/org/:org_name/:product_name/artifacts/:archive_uuid", Live.Archives, :show)

      live("/org/:org_name/:product_name/deployments", Live.Deployments.Index)
      live("/org/:org_name/:product_name/deployments/new", Live.Deployments.New)

lib/nerves_hub/devices/device_health.ex
defmodule NervesHub.Devices.DeviceHealth do
  use Ecto.Schema

  import Ecto.Changeset

  alias NervesHub.Devices.Device

  @type t :: %__MODULE__{}
  @required_params [:device_id, :data]

  schema "device_health" do
    belongs_to(:device, Device)
    field(:data, :map)
    timestamps(type: :utc_datetime_usec, updated_at: false)
  end

  def save(params) do
    %__MODULE__{}
    |> cast(params, @required_params)
    |> validate_required(@required_params)
  end
end

apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex
defmodule NervesHubWWWWeb.DeviceView do
  use NervesHubWWWWeb, :view

  alias NervesHubDevice.Presence
  alias NervesHubWebCore.Repo
  alias NervesHubWWWWeb.LayoutView.DateTimeFormat, as: DateTimeFormat

  import NervesHubWWWWeb.LayoutView,
    only: [pagination_links: 1, user_orgs: 1, user_org_products: 2]

  import NervesHubWWWWeb.OrgCertificateView, only: [format_serial: 1]

  def architecture_options do
    [
      "aarch64",
      "arm",
      "mipsel",
      "x86",
      "x86_atom",
      "x86_64"
    ]
  end

  def devices_table_header(title, value, current_sort, sort_direction \\ :asc)

  def devices_table_header(title, value, current_sort, sort_direction)
      when value == current_sort do
    caret_class = if sort_direction == :asc, do: "up", else: "down"

    content_tag(:th, phx_click: "sort", phx_value_sort: value, class: "pointer sort-selected") do
      [title, content_tag(:i, "", class: "icon-caret icon-caret-#{caret_class}")]
    end
  end

  def devices_table_header(title, value, _current_sort, _sort_direction) do
    content_tag(:th, title, phx_click: "sort", phx_value_sort: value, class: "pointer")
  end

  def display_status(status) when is_binary(status) do
    status
    |> String.split("-")
    |> Enum.join(" ")
  end

  def display_status(_), do: nil

  def platform_options do
    [
      "bbb",
      "ev3",
      "qemu_arm",
      "rpi",
      "rpi0",
      "rpi2",
      "rpi3",
      "smartrent_hub",
      "x86_64"
    ]
  end

  def tags_to_string(%Ecto.Changeset{} = changeset) do
    changeset
    |> Ecto.Changeset.get_field(:tags)
    |> tags_to_string()
  end

  def tags_to_string(%{tags: tags}), do: tags_to_string(tags)
  def tags_to_string(tags) when is_list(tags), do: Enum.join(tags, ",")
  def tags_to_string(tags), do: tags

  defdelegate device_status(device), to: Presence

  def selected?(filters, field, value), do: filters[field] == value

  def move_alert(%{name: product_name}) do
    """
    This will move the selected device(s) to the #{product_name} product

    Any existing firmware keys the devices may use will attempt to be migrated if they do not exist on the target organization.

    Moving devices may also trigger an update if there are matching deployments on the new product. It is up to the user to ensure any required firmware keys are on the device before migrating them to a new product with a new firmware or the device may fail to update.

    Do you wish to continue?
    """
  end
end

lib/nerves_hub_web/templates/device/edit.html.leex
<%= link "Back to Device", to: Routes.device_path(@socket, :show, @org.name, @product.name, @device.identifier), class: "back-link"%>
<h1>Edit Device</h1>

<%= form_for @changeset, "#", [phx_change: :validate, phx_submit: :save], fn f -> %>
  <div class="form-group">
    <label for="identifier_input" class="tooltip-label h3 mb-1">
      <span>ID</span>
      <span class="tooltip-info"></span>
      <span class="tooltip-text">Device ID cannot be changed once created</span>
    </label>
    <%= text_input f, :identifier, class: "form-control", id: "identifier_input", disabled: "true" %>
    <div class="has-error"><%= error_tag f, :identifier %></div>
  </div>

  <div class="form-group">
    <label for="description_input" class="tooltip-label h3 mb-1">
      <span>Description</span>
      <span class="tooltip-info"></span>
      <span class="tooltip-text">Description for this device</span>
    </label>
    <%= text_input f, :description, class: "form-control", id: "description_input" %>
    <div class="has-error"><%= error_tag f, :description %></div>
  </div>

  <div class="form-group">
    <label for="tags" class="tooltip-label h3 mb-1">
      <span>Tag(s)</span>
      <span class="tooltip-info"></span>
      <span class="tooltip-text">Use tags to manage firmware deployments for different sets of devices.</span>
    </label>
    <%= text_input f, :tags, class: "form-control", id: "tags", value: tags_to_string(@changeset) %>
    <small class="form-text text-muted mt-1">
      Every device is added to the 'all' tag by default. You can have multiple tags separated by commas.
    </small>
    <div class="has-error"><%= error_tag f, :tags %></div>
  </div>

  <div class="button-submit-wrapper">
    <%= submit "Save Changes", class: "btn btn-primary", disabled: @changeset.errors != [] %>
  </div>
<% end %>

lib/nerves_hub_web/templates/device/show.html.leex
<%= if @device.deleted_at do %>
  <div class="alert alert-danger">
    <div class="content-container">
      <center>Device is deleted and must be restored to use</center>
    </div>
  </div>
<% end %>

<div class="action-row">
  <%= link "All Devices", to: Routes.device_path(@socket, :index, @org.name, @product.name), class: "back-link"%>
  <div class="btn-group" role="group" aria-label="Device Actions">
  <%= if @device.deleted_at do %>
    <button class="btn btn-outline-light btn-action"  aria-label="Restore" type="button" phx-click="restore">
      <span class="button-icon power"></span>
      <span class="action-text">Restore</span>
    </button>
    <button class="btn btn-outline-light btn-action btn-primary" aria-label="Destroy" type="button" phx-click="destroy" data-confirm="Are you sure?">
      <span class="button-icon delete"></span>
      <span class="action-text">Destroy</span>
    </button>
  <% else %>
    <button class="btn btn-outline-light btn-action"  aria-label="Reboot device" type="button" phx-click="reboot" <%= if @device.status == "offline", do: "disabled" %> data-confirm="Are you sure?">
      <span class="button-icon power"></span>
      <span class="action-text">Reboot</span>
    </button>
    <%= link(
      class: "btn btn-outline-light btn-action",
      aria_label: "Console",
      target: "_blank",
      to: Routes.device_path(@socket, :console, @org.name, @product.name, @device.identifier))
      do %>
      <span class="button-icon console-icon"></span>
      <span class="action-text">Console</span>
    <% end %>
    <%= form_for %Plug.Conn{}, "#", [phx_submit: "toggle_health_state"], fn _f -> %>
      <%= submit class: "btn btn-outline-light btn-action", aria_label: (if @device.healthy, do: "Quarantine", else: "Unquarantine") do %>
        <span class="button-icon quarantine"></span>
        <span class="action-text"><%= if @device.healthy, do: "Quarantine", else: "Unquarantine" %></span>
      <% end %>
    <% end %>
    <button class="btn btn-outline-light btn-action" aria-label="Delete" type="button" phx-click="delete" data-confirm="Are you sure?">
      <span class="button-icon delete"></span>
      <span class="action-text">Delete</span>
    </button>
    <%= link(
      class: "btn btn-outline-light btn-action",
      aria_label: "Edit",
      to: Routes.device_path(@socket, :edit, @org.name, @product.name, @device.identifier))
      do %>
      <span class="button-icon edit"></span>
      <span class="action-text">Edit</span>
    <% end %>
  <% end %>

    <a class="btn btn-outline-light btn-action" aria-label="Download Audit Logs" href="<%= Routes.device_path(@socket, :export_audit_logs, @org.name, @product.name, @device.identifier) %>">
      <div class="button-icon download"></div>
      <span class="action-text">Download Audit Logs</span>
    </a>
  </div>
</div>

<%= render("_header.html", device: @device) %>

<div class="row">
  <div class="col-lg-7">
    <h3 class="mb-2">Deployments</h3>
    <div class="display-box">
      <div class="help-text mb-1">Tags</div>
      <%= if !is_nil(@device.tags) do %>
        <%= for tag <- @device.tags do %>
          <span class="badge"><%= tag %></span>
        <% end %>
      <% else %>
        <p>No Tags</p>
      <% end %>
    </div>

    <h3 class="mb-2">Firmware</h3>
    <div class="display-box">
      <div class="flex-row justify-content-between">
        <div>
          <div class="help-text mb-1">Version</div>
          <%= if is_nil(@device.firmware_metadata) do %>
            <p>Unknown</p>
          <% else %>
            <span class="badge">
              <%= @device.firmware_metadata.version %>
            </span>
          <% end %>
        </div>
        <%= if !is_nil(@device.firmware_metadata) do %>
          <div>
            <div class="help-text mb-1">UUID</div>
            <a href="<%= Routes.firmware_path(@socket, :show, @org.name, @product.name, @device.firmware_metadata.uuid) %>" class="badge ff-m"><%= @device.firmware_metadata.uuid %></a>
          </div>
        <% end %>
      </div>
      <div class="mt-4">
        <div class="help-text mb-1">Status</div>
        <div class="tt-c-first-letter">
          <%= cond do %>
            <% @device.status == "offline" -> %>
              <span class="color-white-50">Unknown</span>
            <% @device.status == "online" -> %>
              Up to date
            <% true -> %>
              <%= display_status(@device.status) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-5">
    <%= render(NervesHubWeb.AuditLogView, "_audit_log_feed.html", assigns) %>
  </div>
</div>

<%= if err = live_flash(@flash, :error) do %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" phx-click="clear-flash-error">&times;</button>
    <%= for line <- String.split(err, "\n") do %>
      <p><%= line %></p>
    <% end %>
  </div>
<% end %>

<%= if info = live_flash(@flash, :info) do %>
  <div class="alert alert-info alert-dismissible">
    <button type="button" class="close" phx-click="clear-flash-info">&times;</button>
    <%= info %>
  </div>
<% end %>

<div class="upload-cert-group">
  <h3 class="mb-2">Certificates</h3>
  <%= if @toggle_upload do %>
    <button class="btn btn-primary" type="button" phx-click="toggle-upload" phx-value-toggle="<%= @toggle_upload %>">
      <span class="action-text">Cancel Upload</span>
    </button>
  <% else %>
    <button class="btn btn-outline-light btn-action" type="button" phx-click="toggle-upload" phx-value-toggle="<%= @toggle_upload %>">
      <div class="button-icon add"></div>
    </button>
  <% end %>
</div>

<div class="<%= unless @toggle_upload, do: "hidden" %>">
  <form phx-change="validate-cert" phx-drop-target="<%= @uploads.certificate.ref %>">
    <div class="form-group import-pem">
      <label>Drag or Click to upload</label>
      <%= live_file_input @uploads.certificate, class: "upload-select"%>
    </div>
  </form>
  </br>
</div>

<%= if Enum.any?(@device.device_certificates, & &1.org_id != @device.org_id) do %>
  <div class="alert alert-warning">
    <div class="content-container">
      <center>Device was previously moved and has certificates associated with a Signer CA from another organization</center>
      </br>
      <center>In most cases, this should be okay (or was even intentional), but automatic device certificate creation</center>
      <center>will not work until the Signer CA is also moved the the same organization as this device.</center>
      </br>
      <center>If the intention is leave the Signer CA in the other organization, then this will continue to work</center>
      <center>so long as certificates are managed manually for this device and other metadata, such as the product</center>
      <center>and firmware signing keys appropiately match the existing firmware as well</center>
    </div>
  </div>
<% end %>
<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th>Serial</th>
      <th>Last used</th>
      <th>Not before</th>
      <th>Not after</th>
    </tr>
  </thead>
  <tbody>
    <%= for cert <- @device.device_certificates do %>
      <% mismatch? = cert.org_id != @device.org_id %>
      <tr class="item" style="<%= if mismatch?, do: "border: 2px dashed var(--warning)" %>">
        <td>
          <div class="mobile-label help-text">Serial</div>
          <code class="color-white wb-ba ff-m"><%= format_serial(cert.serial) %></code>
        </td>
        <td title="<%= cert.last_used %>">
          <div class="mobile-label help-text">Last used</div>
          <%= if !is_nil(cert.last_used) do %>
            <%= DateTimeFormat.from_now(cert.last_used) %>
          <% else %>
            <span class="text-muted">Never</span>
          <% end %>
        </td>
        <td>
          <div class="mobile-label help-text">Not before</div>
          <div class="date-time"><%= cert.not_before %></div>
        </td>
        <td>
          <div class="mobile-label help-text">Not after</div>
          <div class="date-time"><%= cert.not_after %></div>
        </td>

        <td class="actions">
          <div class="mobile-label help-text">Actions</div>
          <div class="dropdown options">
              <a class="dropdown-toggle options" href="#" id="<%= cert.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="mobile-label pr-2">Open</div>
                <img src="/images/icons/more.svg" alt="options" />
              </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= if mismatch? do %>
                <%= link("Organization", class: "dropdown-item", aria_label: "Originating Organization", to: Routes.product_path(@socket, :index, Repo.preload(cert, :org).org.name)) %>
              <% end %>
              <%= if cert.der do %>
                <%= link("Download", class: "dropdown-item", aria_label: "Download Device Certificate", to: Routes.device_path(@socket, :download_certificate, @org.name, @product.name, @device.identifier, cert.serial)) %>
              <% end %>
              <a class="dropdown-item" phx-click="delete-certificate" phx-value-serial="<%= cert.serial %>" data-confirm="Delete <%= format_serial(cert.serial) %>?">Delete</a>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>